
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-6
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-6
pull_requests: [{"author":{"id":"U_kgDOBX3DZA","is_bot":false,"login":"yuji-sakaguchi","name":"Yuji Sakaguchi"},"headRefName":"Yuji-RiderNavBarUpdates","number":24,"title":"Yuji RiderNavBar Updates","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/24"},{"author":{"id":"MDQ6VXNlcjMxNTU0NTUw","is_bot":false,"login":"andyinnie","name":"Andrew Martinez"},"headRefName":"liz-ride-table-assigned-column","number":23,"title":"liz - add \"assigned\" column to rides table","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/23"},{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"Lindsey-ApplyButtonBug","number":22,"title":"lw - fixed bug (404 error) on Apply to be a Rider button","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/22"},{"author":{"id":"U_kgDOBXuxuA","is_bot":false,"login":"amisra0","name":""},"headRefName":"AnikaDriversControllerBackend","number":20,"title":"Non-Admin Users CanNOT Access Driver List","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/20"}]
