
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-6
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-6
pull_requests: [{"author":{"id":"MDQ6VXNlcjU1NjAyNjE0","is_bot":false,"login":"jeffsmithepic","name":"Wesley Chiba"},"headRefName":"Wesley-ExposeCommitInfo","number":39,"title":"Wesley - Expose commit info","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/39"},{"author":{"id":"U_kgDOBX3DZA","is_bot":false,"login":"yuji-sakaguchi","name":"Yuji Sakaguchi"},"headRefName":"Yuji-Spring3","number":37,"title":"Yuji - Update Backend code to Spring 3 ","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/37"},{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"Diya-DriverFrontend2","number":36,"title":"Diya driver frontend part 2 of EPIC","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/36"},{"author":{"id":"U_kgDOBX3DZA","is_bot":false,"login":"yuji-sakaguchi","name":"Yuji Sakaguchi"},"headRefName":"YujiDriverIdDropdown","number":35,"title":"Yuji - Dropdown for DriverID in create shifts","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/35"},{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"Lindsey-AcceptRiderModifyRoleFeature","number":34,"title":"Lindsey - Automatically toggle rider role after accepting application feature","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/34"},{"author":{"id":"MDQ6VXNlcjMxNTU0NTUw","is_bot":false,"login":"andyinnie","name":"Andrew Martinez"},"headRefName":"liz-sort-user-table","number":26,"title":"liz - sort users table by default","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/26"},{"author":{"id":"MDQ6VXNlcjU1NjAyNjE0","is_bot":false,"login":"jeffsmithepic","name":"Wesley Chiba"},"headRefName":"Wesley-DriverAvailabilities","number":25,"title":"Wesley driver availabilities","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/25"}]
