
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-6
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-6
pull_requests: [{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"LindseyDriverAvailability","number":54,"title":"Lindsey - Driver Availability Backend + Corresponding Frontend Changes","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/54"},{"author":{"id":"U_kgDOBX3DZA","is_bot":false,"login":"yuji-sakaguchi","name":"Yuji Sakaguchi"},"headRefName":"Yuji-CreateShiftShiftTimes","number":51,"title":"Yuji - Create Shift End Time has to be later than Start Time","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/51"},{"author":{"id":"MDQ6VXNlcjMxNTU0NTUw","is_bot":false,"login":"andyinnie","name":"Andrew Martinez"},"headRefName":"liz-h2-console-navbar","number":46,"title":"liz - h2 console navbar environment variable","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/46"},{"author":{"id":"MDQ6VXNlcjMxNTU0NTUw","is_bot":false,"login":"andyinnie","name":"Andrew Martinez"},"headRefName":"liz-swagger-navbar-env-var","number":43,"title":"liz - swagger navbar environment variable","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/43"}]
