
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-6
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-6
pull_requests: [{"author":{"id":"U_kgDOBXuxuA","is_bot":false,"login":"amisra0","name":""},"headRefName":"AnikaRideDriverAssignShiftForm","number":58,"title":"Anika Ride Request Assign Driver","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/58"},{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"LindseyDriverAvailability","number":54,"title":"Lindsey - Driver Availability Backend + Corresponding Frontend Changes","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/pull/54"}]
